# Request courses
POST http://{{host}}:{{port}}/courses
Authorization: 0928dfa4-2a03-11f1-ae1f-08979874dd67

{
    "name" : "Go Bases",
    "start_date" : "2022-10-01",
    "end_date" : "2023-01-01"
}